# This is a basic workflow to help you get started with Actions

name: wf_notify

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: run notify
        run: echo notify!
