# This is a basic workflow to help you get started with Actions

name: wf_notify

on:
  push:
    branches: [ notify ]
  pull_request:
    branches: [ notify ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.CI_PAT }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Do something with a passing build
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          echo success
          echo ${{ github.ref }}

      - name: Do something with a failing build
        if: steps.wait-for-build.outputs.conclusion == 'failure'
        run: |
          echo failure
          echo ${{ github.ref }}
